# Generated by Django 4.2.4 on 2023-10-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutionapp', '0019_assignmenttable_courseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenttable',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
