# Generated by Django 4.2.4 on 2023-10-21 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutionapp', '0023_leavenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='courseid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutionapp.course'),
        ),
    ]
