# Generated by Django 4.2.4 on 2023-10-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutionapp', '0025_notification_courseid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
    ]
