# Generated by Django 4.2.4 on 2023-10-24 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutionapp', '0026_remove_student_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigntable',
            name='batchid',
        ),
        migrations.RemoveField(
            model_name='assigntable',
            name='studentid',
        ),
        migrations.DeleteModel(
            name='sessiontable',
        ),
    ]
