# Generated by Django 4.2.4 on 2023-10-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutionapp', '0028_teachernotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmenttable',
            old_name='submit_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='assignmenttable',
            name='submit_on',
            field=models.DateField(auto_now=True),
        ),
    ]
